name: Docker Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'nhmesh-telemetry/**'
      - 'docker/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/docker-deploy.yml'

jobs:
  deploy:
    runs-on: collector
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and deploy containers
        run: |
          cd docker
          cp ~/telemetry.env .
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml build --no-cache
          docker compose -f docker-compose.yml up -d --force-recreate
